notifications:
  on_success: change
  on_failure: change

os: linux
language: c++
sudo: required

services:
  - docker

install:
  - docker pull codestand/baseos

script:
  - cp ci/led-blink.config.yaml examples/led-blink/.config.yaml
  - docker run -v $PWD/examples/led-blink:/app -t codestand/baseos
